# docker-compose up -d --build service db

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets
    volumes:
      - ./db/data:/data/db 

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      BLOCKCHAIN_NET: testnet # never change it in production!
      WEBHOOK_LISTENER: http://127.0.0.1/userWalletRefill
    volumes:
      - ./service:/service
    ports:
      - 127.0.0.1:2311:2311 # 127.0.0.1 to make service availble onl locally
    depends_on:
      - db