# docker-compose up -d

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets
    volumes:
      - ./db/data:/data/db
    restart: always

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      BLOCKCHAIN_NET: "testnet" # never change it in production!
      WEBHOOKS_LISTENER: "http://127.0.0.1:80/userWalletRefill"
      COIN_CONTRACT: "0xa99fdf82aa3f22416ac2db749b4ce830870383ff" # REMEMBER to change when in prod
      NFT_CONTRACT: "0x..."
    volumes:
      - ./service:/service
    ports:
      - 127.0.0.1:2311:2311 # 127.0.0.1 to make service availble onl locally
    depends_on:
      - db
    restart: always