# docker-compose up -d 

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets
      MONGO_INITDB_ROOT_USERNAME: wallets-manager-root
      MONGO_INITDB_ROOT_PASSWORD: wallets-manager-password
    volumes: 
      - ./db:/data/db
    ports:
      - '27017-27019:27017-27019'

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      BLOCKCHAIN_NET: testnet
    volumes:
      - ./service:/service
    ports: 
      - 2311:2311