# docker-compose up -d

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets-mainnet
    volumes:
      - ./db/data:/data/db
    restart: always

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      PORT: 2311
      DB_NAME: wallets-mainnet
      BLOCKCHAIN_ID: 56
      BLOCKCHAIN_NODE: https://bsc-dataseed.binance.org/
      COIN_CONTRACT: "0xa99fdf82aa3f22416ac2db749b4ce830870383ff"
      BNB_PRICE: 1000 # OGLC COINS
      EXCHANGE_FEE: 0.05 # = 5%
      WEBHOOKS_LISTENER: https://ogle.money/api/wallet/Chai4aichie7ce2imiesiJ4osheenaeyaeGahShe
    volumes:
      - ./service:/service
    ports:
      - 127.0.0.1:2311:2311 # 127.0.0.1 to make service availble onl locally
    depends_on:
      - db
    restart: always