# docker-compose up -f docker-compose.dev.yml --build service
# After running don't forget to make docker image prune, because there will be extra unused images

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets
    volumes:
      - ./db/data:/data/db
    ports:
      - '27017-27019:27017-27019'

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      BLOCKCHAIN_NET: testnet
      WEBHOOK_LISTENER: http://127.0.0.1:8080/userWalletRefill
    volumes:
      - ./service:/service
    ports:
      - 2311:2311
    depends_on:
      - db