# docker-compose -f docker-compose.testnet.yml up --build service

version: '3.7'

services:

  db:
    image: mongo
    container_name: 'wallets-manager-database'
    environment:
      MONGO_INITDB_DATABASE: wallets-testnet
    volumes:
      - ./db/data:/data/db

  service:
    container_name: 'wallets-manager-service'
    build: ./service
    environment:
      NODE_ENV: ${ENV} 
      PORT: 2311
      DB_NAME: wallets-testnet
      BLOCKCHAIN_ID: 97
      BLOCKCHAIN_NODE: https://data-seed-prebsc-1-s1.binance.org:8545/
      COIN_CONTRACT: "0x5b0150e7cdb02f8498675f8da8d648dee7c79c84"
      BNB_PRICE: ${BNB_PRICE}
      EXCHANGE_FEE: ${EXCHANGE_FEE}
      WEBHOOKS_LISTENER: ${WEBHOOKS_LISTENER}
    volumes:
      - ./service:/service
    ports:
      - 2311:2311
    depends_on:
      - db